const detail = [
    { id: "1",
      name : "Men Shirt",
      price : "760",
      color: "blue",
      imgsrc: "",
      realprice:"1600",
      discount:"50"
    },
    { id: "2",
      name : "Men Jeans",
      price : "760",
      color: "blue",
      imgsrc: "",
      realprice:"1600",
      discount:"50"
    },
    { id: "3",
      name : "Men denim jeans",
      price : "760",
      color: "blue",
      imgsrc: "",
      realprice:"1600",
      discount:"50"
    },
    { id: "4",
      name : "Men yellow shirt",
      price : "760",
      color: "yellow",
      imgsrc: "",
      realprice:"1600",
      discount:"50"
    },
    { id: "5",
      name : "Men Pink shirt",
      price : "760",
      color: "pink",
      imgsrc: "",
      realprice:"1600",
      discount:"50"
    },
    { id: "6",
      name : "Men shoes",
      price : "760",
      color: "black",
      imgsrc: "",
      realprice:"1600",
      discount:"50"
    },
    { id: "7",
      name : "Men black jeans",
      price : "760",
      color: "black",
      imgsrc: "",
      realprice:"1600",
      discount:"50"
    },
    { id: "8",
      name : "Men shoes",
      price : "760",
      color: "blue",
      imgsrc: "",
      realprice:"1600",
      discount:"50"},

]
export {detail as default};